import { type NextPage } from "next";
import Head from "next/head";
import { AdSlotClientSide } from "~/components/AdSlotClientSide";
import { Card } from "~/components/Card";
import { Navbar } from "~/components/Navbar";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="flex flex-col items-center justify-center bg-blue-h5">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            highfivve <span className="text-pink-h5">Demo</span> App
          </h1>
          <div className="flex min-w-full gap-4 md:gap-8">
            <Card title="ad slot 1">
              <AdSlotClientSide id="h5v_content_1" />
            </Card>
            <Card title="ad slot 2"></Card>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
